# Generated by Django 6.0.3 on 2026-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duyuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('kategori', models.CharField(choices=[('belediye', 'Belediye'), ('bamf', 'BAMF'), ('okul', 'Okul / Kreş'), ('is', 'İş & Çalışma'), ('genel', 'Genel')], default='genel', max_length=20)),
                ('kaynak_url', models.URLField(blank=True)),
                ('yayinda', models.BooleanField(default=True)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Duyuru',
                'verbose_name_plural': 'Duyurular',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
