# Generated by Django 5.2.9 on 2026-03-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0003_duyuru_scope_duyuru_stadt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duyuru',
            name='kaynak_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
