# Generated by Django 5.2.9 on 2026-03-25 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0004_alter_duyuru_kaynak_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='kaynak_tipi',
            field=models.CharField(choices=[('konsolosluk', 'T.C. Konsolosluk'), ('belediye', 'Belediye'), ('kullanici', 'Kullanıcı')], default='belediye', max_length=15, verbose_name='Kaynak Tipi'),
        ),
        migrations.AddField(
            model_name='duyuru',
            name='yazar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
