# Generated by Django 5.2.9 on 2026-03-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0005_duyuru_kaynak_tipi_duyuru_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='duyurular/', verbose_name='Resim'),
        ),
    ]
