# Generated by Django 5.2.9 on 2026-03-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duyurular', '0007_eyalet_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='yayin_bitis',
            field=models.DateField(null=True, verbose_name='Yayın Bitiş Tarihi'),
        ),
    ]
