# Generated by Django 6.0.3 on 2026-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('tarih', models.DateField()),
                ('bitis', models.DateField(blank=True, null=True)),
                ('tur', models.CharField(choices=[('resmi_tatil', 'Resmi Tatil'), ('paskalya', 'Paskalya'), ('okul', 'Okul Takvimi'), ('yerel', 'Yerel Etkinlik'), ('ozel', 'Özel Gün')], default='ozel', max_length=20)),
                ('aciklama', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Etkinlik',
                'verbose_name_plural': 'Etkinlikler',
                'ordering': ['tarih'],
            },
        ),
    ]
