# Generated by Django 5.2.9 on 2026-04-08 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadt', '0040_seed_westerburg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='İkon (Bootstrap Icon sınıfı)')),
            ],
            options={
                'verbose_name': 'İşletme Kategorisi',
                'verbose_name_plural': 'İşletme Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_business_module_active', models.BooleanField(default=False, help_text='Navbar menüsü ve tüm işletme sayfaları bu şalterle açılır/kapanır.', verbose_name='İşletme Modülü Aktif')),
            ],
            options={
                'verbose_name': 'Global Ayar',
                'verbose_name_plural': 'Global Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (€)')),
                ('duration_days', models.PositiveIntegerField(help_text='Örn: 30, 90, 365', verbose_name='Süre (Gün)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Abonelik Paketi',
                'verbose_name_plural': 'Abonelik Paketleri',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='LocalBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='İşletme Adı')),
                ('slug', models.SlugField(unique=True, verbose_name='URL Slug')),
                ('slogan', models.CharField(blank=True, max_length=150, verbose_name='Slogan')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='Logo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='businesses/covers/', verbose_name='Kapak Görseli')),
                ('whatsapp_number', models.CharField(blank=True, help_text='+49 ile başlamalı', max_length=30, verbose_name='WhatsApp Numarası')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('website_url', models.URLField(blank=True, verbose_name='Web Sitesi')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitiş Tarihi')),
                ('is_published', models.BooleanField(default=False, verbose_name='Yayında')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Onaylı İşletme')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.businesscategory', verbose_name='Kategori')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='stadt.stadt', verbose_name='Şehir')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='businesses.subscriptionplan', verbose_name='Abonelik Paketi')),
            ],
            options={
                'verbose_name': 'Yerel İşletme',
                'verbose_name_plural': 'Yerel İşletmeler',
                'ordering': ['-created_at'],
            },
        ),
    ]
