# Generated by Django 5.2.9 on 2026-04-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme')),
                ('whatsapp_clicks', models.PositiveIntegerField(default=0, verbose_name='WhatsApp Tıklaması')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='businesses.localbusiness', verbose_name='İşletme')),
            ],
            options={
                'verbose_name': 'İşletme Analitik',
                'verbose_name_plural': 'İşletme Analitikleri',
                'ordering': ['-date'],
                'unique_together': {('business', 'date')},
            },
        ),
    ]
