# Generated by Django 5.2.9 on 2026-04-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businessanalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='localbusiness',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='Dosya yerine harici link kullanmak için', verbose_name='Kapak Görseli URL'),
        ),
        migrations.AddField(
            model_name='localbusiness',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Dosya yerine harici link kullanmak için', verbose_name='Logo URL'),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/covers/', verbose_name='Kapak Görseli (dosya)'),
        ),
        migrations.AlterField(
            model_name='localbusiness',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='businesses/logos/', verbose_name='Logo (dosya)'),
        ),
    ]
