# Generated by Django 6.0.3 on 2026-04-28 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_seed_kategoriler_ve_isletmeler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='localbusiness',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='İşletme Sahibi'),
        ),
        migrations.AlterField(
            model_name='businessanalytics',
            name='date',
            field=models.DateField(verbose_name='Tarih'),
        ),
    ]
