# Generated by Django 5.2.9 on 2026-04-28 11:18

from django.db import migrations


def seed_ucretsiz_plan(apps, schema_editor):
    SubscriptionPlan = apps.get_model('businesses', 'SubscriptionPlan')
    SubscriptionPlan.objects.get_or_create(
        name='Ücretsiz 2026',
        defaults={
            'price': '0.00',
            'duration_days': 365,
            'is_active': True,
        },
    )


def reverse_seed(apps, schema_editor):
    SubscriptionPlan = apps.get_model('businesses', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(name='Ücretsiz 2026').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0005_localbusiness_owner_alter_businessanalytics_date'),
    ]

    operations = [
        migrations.RunPython(seed_ucretsiz_plan, reverse_seed),
    ]
