# Generated by Django 6.0.3 on 2026-03-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('aciklama', models.TextField(blank=True)),
                ('sira', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Forum Kategorisi',
                'verbose_name_plural': 'Forum Kategorileri',
                'ordering': ['sira'],
            },
        ),
        migrations.CreateModel(
            name='Konu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('sabitlendi', models.BooleanField(default=False)),
                ('kapali', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konular', to='forum.forumkategori')),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Konu',
                'verbose_name_plural': 'Konular',
                'ordering': ['-sabitlendi', '-guncelleme'],
            },
        ),
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='forum.konu')),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yorum',
                'verbose_name_plural': 'Yorumlar',
                'ordering': ['olusturulma'],
            },
        ),
    ]
