# Generated by Django 6.0.3 on 2026-03-23 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_konu_options_konu_scope_konu_stadt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konu',
            options={'ordering': ['-sabitlendi', '-guncelleme'], 'verbose_name': 'Konu', 'verbose_name_plural': 'Konular'},
        ),
    ]
