# Generated by Django 5.2.9 on 2026-03-25 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forum_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konu',
            name='resim',
        ),
        migrations.RemoveField(
            model_name='yorum',
            name='resim',
        ),
    ]
