# Generated by Django 5.2.9 on 2026-03-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='biyografi_gizli',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profil',
            name='sehir_gizli',
            field=models.BooleanField(default=False),
        ),
    ]
