# Generated by Django 5.2.9 on 2026-04-08 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profil_biyografi_gizli_profil_sehir_gizli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='sehir',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
