# Generated by Django 6.0.3 on 2026-04-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profil_sehir_default_bos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='completed_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
