# Generated by Django 6.0.3 on 2026-03-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogYazisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('icerik', models.TextField()),
                ('ozet', models.CharField(blank=True, max_length=300)),
                ('yayinda', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('yazar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Yazısı',
                'verbose_name_plural': 'Blog Yazıları',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
