# Generated by Django 6.0.3 on 2026-03-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogyazisi',
            name='kapak_resmi',
            field=models.URLField(blank=True, verbose_name='Kapak Resmi URL'),
        ),
    ]
