# Generated by Django 5.0.4 on 2026-04-07 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_ilk_100_gun_yazilari'),
        ('blog', '0014_kapak_resmi_dosya'),
    ]

    operations = [
    ]