# Generated by Django 5.0.4 on 2026-04-07 16:00

from django.db import migrations

YAZI = {
    'slug': 'rundfunkbeitrag-gez-nedir',
    'baslik': "Rundfunkbeitrag (GEZ) Nedir? Almanya'da TV ve Radyo Vergisi Rehberi",
    'ozet': "Almanya'da her hanenin ödemekle yükümlü olduğu Rundfunkbeitrag (eski adıyla GEZ) nedir, ne kadar ödenir ve nasıl kayıt olunur? Tüm detaylar bu yazıda.",
    'icerik': "<p>Bu sayfa yapım aşamasındadır. Yakında Almanya'da Rundfunkbeitrag (GEZ) süreciyle ilgili detaylı bilgiler eklenecektir.</p>",
}


def ekle(apps, schema_editor):
    BlogYazisi = apps.get_model('blog', 'BlogYazisi')
    User = apps.get_model('auth', 'User')

    yazar = User.objects.filter(is_superuser=True).first() or User.objects.first()

    if not yazar:
        return

    BlogYazisi.objects.get_or_create(
        slug=YAZI['slug'],
        defaults=dict(
            baslik=YAZI['baslik'],
            icerik=YAZI['icerik'],
            ozet=YAZI['ozet'],
            yazar=yazar,
            scope='genel',
            yayinda=True,
        ),
    )

class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_merge_migration'),
    ]

    operations = [
        migrations.RunPython(ekle, migrations.RunPython.noop),
    ]