# Generated by Django 6.0.3 on 2026-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RehberSayfasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('kategori', models.CharField(choices=[('resmi', 'Resmi İşlemler'), ('gunluk', 'Günlük Yaşam'), ('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('ulasim', 'Ulaşım'), ('konut', 'Konut'), ('almanca', 'Almanca Çalışma'), ('gezi', 'Gezi & Kültür')], max_length=20)),
                ('icerik', models.TextField()),
                ('ozet', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='bi-info-circle', max_length=50)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('yayinda', models.BooleanField(default=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rehber Sayfası',
                'verbose_name_plural': 'Rehber Sayfaları',
                'ordering': ['kategori', 'sira'],
            },
        ),
    ]
