# Generated by Django 6.0.3 on 2026-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kaynak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Sadece dahili sayfalar için kullanılır.', max_length=220, null=True, unique=True)),
                ('tip', models.CharField(choices=[('sayfa', 'Dahili Sayfa'), ('link', 'Harici Link')], default='sayfa', max_length=10)),
                ('url', models.URLField(blank=True, help_text='Sadece harici linkler için kullanılır.')),
                ('kategori', models.CharField(choices=[('resmi', 'Resmi İşlemler & Kurumlar'), ('ilan', 'İlan Platformları'), ('is', 'İş & Kariyer'), ('konut', 'Konut'), ('egitim', 'Eğitim'), ('saglik', 'Sağlık'), ('ulasim', 'Ulaşım'), ('almanca', 'Almanca Öğrenimi'), ('gunluk', 'Günlük Yaşam'), ('gezi', 'Gezi & Kültür'), ('haber', 'Haber & Bilgi'), ('diger', 'Diğer')], max_length=20)),
                ('icerik', models.TextField(blank=True, help_text='Sadece dahili sayfalar için kullanılır.')),
                ('ozet', models.CharField(blank=True, max_length=300)),
                ('icon', models.CharField(default='bi-info-circle', max_length=50)),
                ('sira', models.PositiveIntegerField(default=0)),
                ('yayinda', models.BooleanField(default=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kaynak',
                'verbose_name_plural': 'Kaynaklar',
                'ordering': ['kategori', 'sira'],
            },
        ),
        migrations.DeleteModel(
            name='RehberSayfasi',
        ),
    ]
