# Generated by Django 6.0.3 on 2026-03-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0002_kaynak_delete_rehbersayfasi'),
    ]

    operations = [
    ]
