# Generated by Django 6.0.3 on 2026-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0018_is_kaynak_temizlik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaynak',
            name='scope',
            field=models.CharField(choices=[('stadt', 'Şehre Özel'), ('eyalet', 'Eyalet Geneli'), ('almanya', 'Tüm Almanya')], default='eyalet', max_length=10, verbose_name='Kapsam'),
        ),
    ]
