# Generated by Django 5.2.9 on 2026-04-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rehber', '0026_seed_frankenthal_kaynaklar'),
        ('rehber', '0034_yeni_belgeler_ekle'),
    ]

    operations = [
    ]
