# Generated by Django 6.0.3 on 2026-03-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='icerik',
            field=models.TextField(blank=True, verbose_name='Blog İçeriği (HTML)'),
        ),
        migrations.AddField(
            model_name='yer',
            name='kapak_resmi',
            field=models.URLField(blank=True, verbose_name='Kapak Resmi URL'),
        ),
        migrations.AddField(
            model_name='yer',
            name='wikipedia_url',
            field=models.URLField(blank=True, verbose_name='Wikipedia Kaynak URL'),
        ),
    ]
