# Generated by Django 5.2.9 on 2026-03-23 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0004_pratik_yerler'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamPaketi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Paket Adı')),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Fiyat (€)')),
                ('sure_etiketi', models.CharField(default='/ ay', help_text='Örn: "/ ay", "/ 3 ay"', max_length=50, verbose_name='Süre Etiketi')),
                ('ozellikler', models.TextField(help_text='Her satır bir özellik olarak gösterilir', verbose_name='Özellikler')),
                ('renk', models.CharField(default='primary', help_text='primary, warning, success, dark...', max_length=30, verbose_name='Bootstrap Renk')),
                ('vurgulu', models.BooleanField(default=False, help_text='En popüler / tavsiye edilen paket', verbose_name='Vurgulu Göster')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('iletisim_notu', models.TextField(blank=True, help_text='Sayfanın altında gösterilecek metin', verbose_name='İletişim Notu')),
            ],
            options={
                'verbose_name': 'Reklam Paketi',
                'verbose_name_plural': 'Reklam Paketleri',
                'ordering': ['sira'],
            },
        ),
        migrations.AddField(
            model_name='yer',
            name='calisma_saati',
            field=models.CharField(blank=True, help_text='Örn: Pzt-Cum 09:00-18:00', max_length=200, verbose_name='Çalışma Saatleri'),
        ),
        migrations.AddField(
            model_name='yer',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='yer',
            name='paket',
            field=models.CharField(choices=[('ucretsiz', 'Ücretsiz'), ('standart', 'Standart'), ('one_cikan', 'Öne Çıkan')], default='ucretsiz', max_length=10, verbose_name='Paket'),
        ),
        migrations.AddField(
            model_name='yer',
            name='paket_bitis',
            field=models.DateField(blank=True, null=True, verbose_name='Paket Bitiş Tarihi'),
        ),
        migrations.AddField(
            model_name='yer',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Sadece rakamlar, örn: 4917612345678', max_length=20, verbose_name='WhatsApp'),
        ),
        migrations.CreateModel(
            name='YerFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Fotoğraf URL')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('yer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotolar', to='yerler.yer', verbose_name='Yer')),
            ],
            options={
                'verbose_name': 'Yer Fotoğrafı',
                'verbose_name_plural': 'Yer Fotoğrafları',
                'ordering': ['sira'],
            },
        ),
    ]
