# Generated by Django 6.0.3 on 2026-03-25 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0008_seed_eyaletler'),
        ('yerler', '0010_seed_reklam_paketleri'),
    ]

    operations = [
        migrations.AddField(
            model_name='yer',
            name='eyalet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yerler', to='stadt.eyalet', verbose_name='Eyalet'),
        ),
    ]
