# Generated by Django 5.2.9 on 2026-04-01 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0028_seed_frankenthal_yerler'),
        ('yerler', '0030_seed_bad_kreuznach_yerler'),
    ]

    operations = [
    ]
