# Generated by Django 5.2.9 on 2026-04-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yerler', '0037_seed_koblenz_yerler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yer',
            options={'ordering': ['kategori', 'sira', 'ad'], 'verbose_name': 'Yer', 'verbose_name_plural': 'Yerler'},
        ),
        migrations.AddField(
            model_name='yer',
            name='sira',
            field=models.PositiveSmallIntegerField(default=0, help_text='Küçük sayı önce gösterilir', verbose_name='Sıra'),
        ),
    ]
