# Generated by Django 6.0.3 on 2026-03-19 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('kategori', models.CharField(choices=[('arac_satilik', 'Araç Satılık'), ('arac_araniyor', 'Araç Aranıyor'), ('ev_kiralik', 'Ev / Daire Kiralık'), ('ev_araniyor', 'Ev / Oda Aranıyor'), ('diger', 'Diğer')], max_length=20)),
                ('fiyat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('iletisim', models.EmailField(max_length=254)),
                ('aktif', models.BooleanField(default=True)),
                ('onaylandi', models.BooleanField(default=False)),
                ('olusturulma', models.DateTimeField(auto_now_add=True)),
                ('sahip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
                'ordering': ['-olusturulma'],
            },
        ),
    ]
