# Generated by Django 6.0.3 on 2026-03-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilan',
            name='kategori',
            field=models.CharField(choices=[('arac_satilik', 'Araç Satılık'), ('ev_kiralik', 'Ev / Daire Kiralık'), ('esya_satilik', 'Eşya / Mobilya Satılık'), ('diger_satilik', 'Diğer Satılık'), ('arac_araniyor', 'Araç Aranıyor'), ('ev_araniyor', 'Ev / Oda Aranıyor'), ('is_araniyor', 'İş Arıyorum'), ('eleman_araniyor', 'Eleman Aranıyor'), ('esya_araniyor', 'Eşya / Mobilya Aranıyor'), ('diger_araniyor', 'Diğer Aranıyor')], max_length=20),
        ),
    ]
