# Generated by Django 5.2.9 on 2026-03-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilan', '0003_ilan_scope_ilan_stadt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ilan',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='ilan/', verbose_name='Resim'),
        ),
    ]
