# Generated by Gemini

from django.db import migrations

CITY_DATA = {
    'mainz': {
        'rss': 'https://www.mainz.de/verwaltung-politik/verwaltungsorganisation/presseservice/pressemeldungen.php'
    },
    'mainz-bingen': {
        'rss': 'https://www.mainz-bingen.de/de/aktuelles/pressemeldungen/pressemeldungen.php'
    },
    'hamburg': {
        'rss': 'https://www.hamburg.de/presse/'
    },
    'mannheim': {
        'rss': 'https://www.mannheim.de/de/nachrichten'
    },
    'stuttgart': {
        'rss': 'https://www.stuttgart.de/aktuelles/'
    },
    'wiesbaden': {
        'rss': 'https://www.wiesbaden.de/medien/pressemitteilungen/index.php'
    },
    'berlin': {
        'rss': 'https://www.berlin.de/presse/'
    },
}

def update_cities_rss(apps, schema_editor):
    Stadt = apps.get_model('stadt', 'Stadt')
    for slug, data in CITY_DATA.items():
        try:
            sehir = Stadt.objects.get(slug=slug)
            sehir.rss_duyuru_url = data['rss']
            sehir.save(update_fields=['rss_duyuru_url'])
        except Stadt.DoesNotExist:
            # Şehir bulunamazsa atla
            continue

def reverse_rss_update(apps, schema_editor):
    # Bu data migration'ı geri almak için özel bir şey yapmaya gerek yok.
    # Alanları boşaltmak bir seçenek olabilir ancak en temizi pass geçmek.
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0014_add_rss_duyuru_url'),
    ]

    operations = [
        migrations.RunPython(update_cities_rss, reverse_rss_update),
    ]
