# Generated by Django 5.2.9 on 2026-04-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadt', '0036_kapak_resmi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyalet',
            name='arma_url',
            field=models.URLField(blank=True, verbose_name='Arma/Bayrak URL'),
        ),
    ]
